# Generated by Django 2.2.2 on 2019-07-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('in_principle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Products')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complianceform.Versions')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complianceform.Entries')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complianceform.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='VersionToQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complianceform.Questions')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complianceform.Versions')),
            ],
            options={
                'unique_together': {('version_id', 'question_id')},
            },
        ),
    ]
