# Generated by Django 2.2.4 on 2019-08-19 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JotFormIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle', models.IntegerField()),
                ('jotform_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('in_principle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('principle', models.IntegerField()),
                ('jotform_submission_id', models.CharField(max_length=30)),
                ('score', models.FloatField(default=0, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Products')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complianceform.Versions')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complianceform.Entries')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complianceform.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='VersionToQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complianceform.Questions')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complianceform.Versions')),
            ],
            options={
                'unique_together': {('version_id', 'question_id')},
            },
        ),
    ]
