# Generated by Django 2.1.7 on 2019-07-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('In_Principle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Online_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Version_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complianceform.Questions')),
                ('Version_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complianceform.Version')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='version_question',
            unique_together={('Version_ID', 'Question_ID')},
        ),
    ]
