# Generated by Django 2.2.2 on 2019-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complianceform', '0005_auto_20190730_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='jotform_submission_id',
            field=models.CharField(max_length=30),
        ),
    ]
