# Generated by Django 2.2.4 on 2019-08-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complianceform', '0006_auto_20190730_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
