# Generated by Django 2.1.7 on 2019-07-20 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_Date', models.DateField()),
                ('Category', models.CharField(max_length=30)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=20)),
                ('Is_Supplier', models.BooleanField()),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Organisation', models.CharField(max_length=50)),
                ('Town_City', models.CharField(max_length=20)),
                ('Post_Code', models.CharField(max_length=10)),
                ('Phone', models.IntegerField(max_length=11)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='userauth',
            name='User_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserDetail'),
        ),
        migrations.AddField(
            model_name='products',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserDetail'),
        ),
    ]
