# Generated by Django 2.1.7 on 2019-07-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='User_ID',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='id',
        ),
        migrations.AlterField(
            model_name='userauth',
            name='User_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.UserDetail'),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
