# Generated by Django 2.2.2 on 2019-07-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190720_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='Email',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Phone',
            field=models.CharField(max_length=20),
        ),
    ]
