# Generated by Django 2.2.2 on 2019-07-30 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190728_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='added_date',
            field=models.DateField(default=datetime.date(2019, 7, 30)),
        ),
    ]
