# Generated by Django 2.2.2 on 2019-07-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190722_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Added_Date',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='User_ID',
            new_name='user_ID',
        ),
        migrations.RenameField(
            model_name='userauth',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userauth',
            old_name='User_ID',
            new_name='user_iD',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='Is_Supplier',
            new_name='is_supplier',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='Organisation',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='Post_Code',
            new_name='post_code',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='Town_City',
            new_name='town_city',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='Username',
            new_name='username',
        ),
    ]
