# Generated by Django 2.2.4 on 2019-08-07 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190730_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='added_date',
            field=models.DateField(default=datetime.date(2019, 8, 7)),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Diagnostic', 'Diagnostic'), ('Therapeutic', 'Therapeutic'), ('Population health', 'Population health'), ('Care-based', 'Care-based'), ('Triage', 'Triage'), ('Self-care', 'Self-care'), ('Health promotion', 'Health promotion'), ('Remote Monitoring', 'Remote Monitoring'), ('Remote Consultation', 'Remote Consultation'), ('Other (please specify)', 'Other (please specify)')], default='Diagnostic', max_length=30),
        ),
    ]
