# Generated by Django 2.2.4 on 2019-08-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190807_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='deploy_point',
            field=models.CharField(choices=[('Primary Care', 'Primary Care'), ('Secondary Care', 'Secondary Care'), ('Community Care', 'Community Care'), ('Tertiary Care', 'Tertiary Care'), ('Individual Care of Self e.g. user’s home/office', 'Individual Care of Self e.g. user’s home/office'), ('For the purposes of population screening', 'For the purposes of population screening'), ('Other', 'Other (please specify)')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='other_category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='other_deploy_point',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Diagnostic', 'Diagnostic'), ('Therapeutic', 'Therapeutic'), ('Population health', 'Population health'), ('Care-based', 'Care-based'), ('Triage', 'Triage'), ('Self-care', 'Self-care'), ('Health promotion', 'Health promotion'), ('Remote Monitoring', 'Remote Monitoring'), ('Remote Consultation', 'Remote Consultation'), ('Other', 'Other (please specify)')], max_length=30),
        ),
    ]
