# Generated by Django 2.2.2 on 2019-07-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190722_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='organisation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='post_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='town_city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
