# Generated by Django 2.2.4 on 2019-08-07 12:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190807_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='deploy_point',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Primary Care', 'Primary Care'), ('Secondary Care', 'Secondary Care'), ('Community Care', 'Community Care'), ('Tertiary Care', 'Tertiary Care'), ('Individual Care of Self e.g. user’s home/office', 'Individual Care of Self e.g. user’s home/office'), ('For the purposes of population screening', 'For the purposes of population screening'), ('Other', 'Other (please specify)')], default='other', max_length=100, verbose_name='At which point of care do you expect your data-driven solution to be deployed? Select as many as applicable.'),
        ),
    ]
