# Generated by Django 2.2.2 on 2019-07-23 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190723_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
