# Generated by Django 2.2.2 on 2019-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190723_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='user_ID',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='product name', max_length=100),
        ),
    ]
