# Generated by Django 2.2.4 on 2019-08-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190807_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='Are you a supplier?'),
        ),
    ]
