# Generated by Django 2.2.4 on 2019-08-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190811_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='principle_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='principle_10',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='principle_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='principle_3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='principle_4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='principle_5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='principle_6',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='principle_7',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='principle_8',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='principle_9',
            field=models.FloatField(default=0),
        ),
    ]
